/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RateRouteImport } from './routes/rate'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CanonsRouteImport } from './routes/canons'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PalateIndexRouteImport } from './routes/palate.index'
import { Route as WineIdRouteImport } from './routes/wine.$id'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ScanListRouteImport } from './routes/scan.list'
import { Route as ScanBottleRouteImport } from './routes/scan.bottle'
import { Route as PalateVerifyRouteImport } from './routes/palate.verify'
import { Route as PalateTypeRouteImport } from './routes/palate.$type'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as AdminTypeFixRouteImport } from './routes/admin.type-fix'
import { Route as AdminInspectRouteImport } from './routes/admin.inspect'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminCorrectionsRouteImport } from './routes/admin.corrections'
import { Route as AdminConsensusRouteImport } from './routes/admin.consensus'
import { Route as AddFriendUsernameRouteImport } from './routes/add-friend.$username'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonsRoute = CanonsRouteImport.update({
  id: '/canons',
  path: '/canons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PalateIndexRoute = PalateIndexRouteImport.update({
  id: '/palate/',
  path: '/palate/',
  getParentRoute: () => rootRouteImport,
} as any)
const WineIdRoute = WineIdRouteImport.update({
  id: '/wine/$id',
  path: '/wine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanListRoute = ScanListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ScanRoute,
} as any)
const ScanBottleRoute = ScanBottleRouteImport.update({
  id: '/bottle',
  path: '/bottle',
  getParentRoute: () => ScanRoute,
} as any)
const PalateVerifyRoute = PalateVerifyRouteImport.update({
  id: '/palate/verify',
  path: '/palate/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PalateTypeRoute = PalateTypeRouteImport.update({
  id: '/palate/$type',
  path: '/palate/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTypeFixRoute = AdminTypeFixRouteImport.update({
  id: '/admin/type-fix',
  path: '/admin/type-fix',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInspectRoute = AdminInspectRouteImport.update({
  id: '/admin/inspect',
  path: '/admin/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/admin/disputes',
  path: '/admin/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCorrectionsRoute = AdminCorrectionsRouteImport.update({
  id: '/admin/corrections',
  path: '/admin/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsensusRoute = AdminConsensusRouteImport.update({
  id: '/admin/consensus',
  path: '/admin/consensus',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFriendUsernameRoute = AddFriendUsernameRouteImport.update({
  id: '/add-friend/$username',
  path: '/add-friend/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/canons': typeof CanonsRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/rate': typeof RateRoute
  '/scan': typeof ScanRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/add-friend/$username': typeof AddFriendUsernameRoute
  '/admin/consensus': typeof AdminConsensusRoute
  '/admin/corrections': typeof AdminCorrectionsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/inspect': typeof AdminInspectRoute
  '/admin/type-fix': typeof AdminTypeFixRoute
  '/admin/usage': typeof AdminUsageRoute
  '/palate/$type': typeof PalateTypeRoute
  '/palate/verify': typeof PalateVerifyRoute
  '/scan/bottle': typeof ScanBottleRoute
  '/scan/list': typeof ScanListRoute
  '/u/$username': typeof UUsernameRoute
  '/wine/$id': typeof WineIdRoute
  '/palate/': typeof PalateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/canons': typeof CanonsRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/rate': typeof RateRoute
  '/scan': typeof ScanRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/add-friend/$username': typeof AddFriendUsernameRoute
  '/admin/consensus': typeof AdminConsensusRoute
  '/admin/corrections': typeof AdminCorrectionsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/inspect': typeof AdminInspectRoute
  '/admin/type-fix': typeof AdminTypeFixRoute
  '/admin/usage': typeof AdminUsageRoute
  '/palate/$type': typeof PalateTypeRoute
  '/palate/verify': typeof PalateVerifyRoute
  '/scan/bottle': typeof ScanBottleRoute
  '/scan/list': typeof ScanListRoute
  '/u/$username': typeof UUsernameRoute
  '/wine/$id': typeof WineIdRoute
  '/palate': typeof PalateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/canons': typeof CanonsRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/rate': typeof RateRoute
  '/scan': typeof ScanRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/add-friend/$username': typeof AddFriendUsernameRoute
  '/admin/consensus': typeof AdminConsensusRoute
  '/admin/corrections': typeof AdminCorrectionsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/inspect': typeof AdminInspectRoute
  '/admin/type-fix': typeof AdminTypeFixRoute
  '/admin/usage': typeof AdminUsageRoute
  '/palate/$type': typeof PalateTypeRoute
  '/palate/verify': typeof PalateVerifyRoute
  '/scan/bottle': typeof ScanBottleRoute
  '/scan/list': typeof ScanListRoute
  '/u/$username': typeof UUsernameRoute
  '/wine/$id': typeof WineIdRoute
  '/palate/': typeof PalateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/canons'
    | '/feed'
    | '/friends'
    | '/rate'
    | '/scan'
    | '/wishlist'
    | '/add-friend/$username'
    | '/admin/consensus'
    | '/admin/corrections'
    | '/admin/data'
    | '/admin/disputes'
    | '/admin/inspect'
    | '/admin/type-fix'
    | '/admin/usage'
    | '/palate/$type'
    | '/palate/verify'
    | '/scan/bottle'
    | '/scan/list'
    | '/u/$username'
    | '/wine/$id'
    | '/palate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/canons'
    | '/feed'
    | '/friends'
    | '/rate'
    | '/scan'
    | '/wishlist'
    | '/add-friend/$username'
    | '/admin/consensus'
    | '/admin/corrections'
    | '/admin/data'
    | '/admin/disputes'
    | '/admin/inspect'
    | '/admin/type-fix'
    | '/admin/usage'
    | '/palate/$type'
    | '/palate/verify'
    | '/scan/bottle'
    | '/scan/list'
    | '/u/$username'
    | '/wine/$id'
    | '/palate'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/canons'
    | '/feed'
    | '/friends'
    | '/rate'
    | '/scan'
    | '/wishlist'
    | '/add-friend/$username'
    | '/admin/consensus'
    | '/admin/corrections'
    | '/admin/data'
    | '/admin/disputes'
    | '/admin/inspect'
    | '/admin/type-fix'
    | '/admin/usage'
    | '/palate/$type'
    | '/palate/verify'
    | '/scan/bottle'
    | '/scan/list'
    | '/u/$username'
    | '/wine/$id'
    | '/palate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CanonsRoute: typeof CanonsRoute
  FeedRoute: typeof FeedRoute
  FriendsRoute: typeof FriendsRoute
  RateRoute: typeof RateRoute
  ScanRoute: typeof ScanRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  AddFriendUsernameRoute: typeof AddFriendUsernameRoute
  AdminConsensusRoute: typeof AdminConsensusRoute
  AdminCorrectionsRoute: typeof AdminCorrectionsRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminInspectRoute: typeof AdminInspectRoute
  AdminTypeFixRoute: typeof AdminTypeFixRoute
  AdminUsageRoute: typeof AdminUsageRoute
  PalateTypeRoute: typeof PalateTypeRoute
  PalateVerifyRoute: typeof PalateVerifyRoute
  UUsernameRoute: typeof UUsernameRoute
  WineIdRoute: typeof WineIdRoute
  PalateIndexRoute: typeof PalateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canons': {
      id: '/canons'
      path: '/canons'
      fullPath: '/canons'
      preLoaderRoute: typeof CanonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palate/': {
      id: '/palate/'
      path: '/palate'
      fullPath: '/palate/'
      preLoaderRoute: typeof PalateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wine/$id': {
      id: '/wine/$id'
      path: '/wine/$id'
      fullPath: '/wine/$id'
      preLoaderRoute: typeof WineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/list': {
      id: '/scan/list'
      path: '/list'
      fullPath: '/scan/list'
      preLoaderRoute: typeof ScanListRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/bottle': {
      id: '/scan/bottle'
      path: '/bottle'
      fullPath: '/scan/bottle'
      preLoaderRoute: typeof ScanBottleRouteImport
      parentRoute: typeof ScanRoute
    }
    '/palate/verify': {
      id: '/palate/verify'
      path: '/palate/verify'
      fullPath: '/palate/verify'
      preLoaderRoute: typeof PalateVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palate/$type': {
      id: '/palate/$type'
      path: '/palate/$type'
      fullPath: '/palate/$type'
      preLoaderRoute: typeof PalateTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/type-fix': {
      id: '/admin/type-fix'
      path: '/admin/type-fix'
      fullPath: '/admin/type-fix'
      preLoaderRoute: typeof AdminTypeFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inspect': {
      id: '/admin/inspect'
      path: '/admin/inspect'
      fullPath: '/admin/inspect'
      preLoaderRoute: typeof AdminInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/corrections': {
      id: '/admin/corrections'
      path: '/admin/corrections'
      fullPath: '/admin/corrections'
      preLoaderRoute: typeof AdminCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consensus': {
      id: '/admin/consensus'
      path: '/admin/consensus'
      fullPath: '/admin/consensus'
      preLoaderRoute: typeof AdminConsensusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-friend/$username': {
      id: '/add-friend/$username'
      path: '/add-friend/$username'
      fullPath: '/add-friend/$username'
      preLoaderRoute: typeof AddFriendUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScanRouteChildren {
  ScanBottleRoute: typeof ScanBottleRoute
  ScanListRoute: typeof ScanListRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanBottleRoute: ScanBottleRoute,
  ScanListRoute: ScanListRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CanonsRoute: CanonsRoute,
  FeedRoute: FeedRoute,
  FriendsRoute: FriendsRoute,
  RateRoute: RateRoute,
  ScanRoute: ScanRouteWithChildren,
  WishlistRoute: WishlistRoute,
  AddFriendUsernameRoute: AddFriendUsernameRoute,
  AdminConsensusRoute: AdminConsensusRoute,
  AdminCorrectionsRoute: AdminCorrectionsRoute,
  AdminDataRoute: AdminDataRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminInspectRoute: AdminInspectRoute,
  AdminTypeFixRoute: AdminTypeFixRoute,
  AdminUsageRoute: AdminUsageRoute,
  PalateTypeRoute: PalateTypeRoute,
  PalateVerifyRoute: PalateVerifyRoute,
  UUsernameRoute: UUsernameRoute,
  WineIdRoute: WineIdRoute,
  PalateIndexRoute: PalateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
