/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RateRouteImport } from './routes/rate'
import { Route as PourRouteImport } from './routes/pour'
import { Route as MyRatingsRouteImport } from './routes/my-ratings'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddFriendUsernameRouteImport } from './routes/add-friend.$username'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const PourRoute = PourRouteImport.update({
  id: '/pour',
  path: '/pour',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRatingsRoute = MyRatingsRouteImport.update({
  id: '/my-ratings',
  path: '/my-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFriendUsernameRoute = AddFriendUsernameRouteImport.update({
  id: '/add-friend/$username',
  path: '/add-friend/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/my-ratings': typeof MyRatingsRoute
  '/pour': typeof PourRoute
  '/rate': typeof RateRoute
  '/scan': typeof ScanRoute
  '/add-friend/$username': typeof AddFriendUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/my-ratings': typeof MyRatingsRoute
  '/pour': typeof PourRoute
  '/rate': typeof RateRoute
  '/scan': typeof ScanRoute
  '/add-friend/$username': typeof AddFriendUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/my-ratings': typeof MyRatingsRoute
  '/pour': typeof PourRoute
  '/rate': typeof RateRoute
  '/scan': typeof ScanRoute
  '/add-friend/$username': typeof AddFriendUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/my-ratings'
    | '/pour'
    | '/rate'
    | '/scan'
    | '/add-friend/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/my-ratings'
    | '/pour'
    | '/rate'
    | '/scan'
    | '/add-friend/$username'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/my-ratings'
    | '/pour'
    | '/rate'
    | '/scan'
    | '/add-friend/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  MyRatingsRoute: typeof MyRatingsRoute
  PourRoute: typeof PourRoute
  RateRoute: typeof RateRoute
  ScanRoute: typeof ScanRoute
  AddFriendUsernameRoute: typeof AddFriendUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour': {
      id: '/pour'
      path: '/pour'
      fullPath: '/pour'
      preLoaderRoute: typeof PourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-ratings': {
      id: '/my-ratings'
      path: '/my-ratings'
      fullPath: '/my-ratings'
      preLoaderRoute: typeof MyRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-friend/$username': {
      id: '/add-friend/$username'
      path: '/add-friend/$username'
      fullPath: '/add-friend/$username'
      preLoaderRoute: typeof AddFriendUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  MyRatingsRoute: MyRatingsRoute,
  PourRoute: PourRoute,
  RateRoute: RateRoute,
  ScanRoute: ScanRoute,
  AddFriendUsernameRoute: AddFriendUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
